 must be unique in a given SonarQube instance
sonar.projectKey=slskirjasto
# this is the name and version displayed in the SonarQube UI. Was mandatory prior to SonarQube 6.1.
sonar.projectName=SLSKirjasto
sonar.projectVersion=1.0
sonar.host.url=http://jeeves:9000
 
# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# This property is optional if sonar.modules is set. 
sonar.sources=.
 
# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

sonar.php.coverage.reportPaths=build/phpunit/coverage.xml
sonar.php.tests.reportPath=build/phpunit/log.xml
sonar.exclusions=tests/**/*,web/vendor/**/*,teststubs/**/*,build/**/*,docs/**/*,mosBase/**/*,phpdocs/**/*,web/css/bootstrap-3.3.4-dist/**/*,build.xml
